export default function Footer() {
  return (
    <footer className="bg-slate-900 text-slate-400 py-8 px-6 text-center border-t border-slate-800">
      <div className="max-w-6xl mx-auto">
        <p className="text-sm font-light">
          &copy; {new Date().getFullYear()} AI Vision. All rights reserved.
        </p>
        <p className="text-xs mt-2 font-light">
          Concept generated by <span className="text-slate-200 font-medium">Deepak</span>
        </p>
      </div>
    </footer>
  )
}
